### ISSUE TITLE
Feature request: import/export through ConfigExporter API

### ISSUE THREAD

**Issue by LukpoDevs** [Appdynamics/api-commandline-tool#33]
Hi team,

I'd like to ask for a feature in which we could export and import Information Points Configuration, using the API of ConfigExporter. 

Accept: application/json
Content-Type: application/json

### **POST /api/rest/app-config**
This API is to copy the configuration from one controller/application to another controller/application. The following example uses a file content.json as the request body.

curl -H "Content-Type: application/json" --data @content.json http://localhost:8080/api/rest/app-config
 
Create a file named content.json as
----
{
  "srcControllerId":87441211 ,
  "destControllerId":87441211 ,
  "srcApplicationId":8,
  "destApplicationId":16,
  "configNames":[
        "INFORMATION_POINTS"
   ],
  "properties":{
    "overwrite": false,
    "createTier": true
  }
}

, where the source/destination controller and application ids should be provided by the user to the content.json file. The port of ConfigExporter can be set by passing property to Java process: -Dserver.port=<desired-port>

Please let me know if there is more information required.

Thanks,
Łukasz

**Comment by svrnm** [comment]
> I'd like to ask for a feature in which we could export and import Information Points Configuration, using the API of ConfigExporter.

This tool here is only for interacting with the controller, not ConfigExporter or any other endpoint. It's possible to add features for Information Points export/import through controller APIs.

**Comment by LukpoDevs** [comment]
Hi @svrnm ,

thank you for responding me! 
Please see required endpoints:
GET /controller/restui/informationPointUiService/getAllInfoPointGathererConfigsForApplication/{applicationId}
POST /controller/restui/informationPointUiService/createInfoPointGathererConfig

Thanks,
Łukasz

**Comment by svrnm** [comment]
@LukpoDevs please checkout the latest commit: https://github.com/Appdynamics/api-commandline-tool/commit/4c2d9a48c1272ccab4fc3b39e3a7d11027e146dc, it contains all you need for information points:

```yaml
informationPoint:
  title: Information Points
  descripion: Retrieve, create and modify information points.
  list:
    title: List information points.
    description: Provide an application id (-a) and a time range string (-t) as parameters.
    example: -a 6743 -t last_1_hour.BEFORE_NOW.-1.-1.60
    method: GET
    endpoint: /controller/restui/informationPointUiService/getAllInfoPointsListViewData/{{a:application}}?time-range={{t:timerange}}
  create:
    title: Create an information point.
    description: Provide an json file (with @ as prefix) containing the information point config (-d) as parameter.
    example: -d @examples/information_point.json
    method: POST
    endpoint: /controller/restui/informationPointUiService/createInfoPointGathererConfig
    payload: {{d:infopoint_config}}
  update:
    title: Update an information point.
    description: Provide an json file (with @ as prefix) containing the information point update config (-d) as parameter.
    example: -d @examples/information_point_update.json
    method: POST
    endpoint: /controller/restui/informationPointUiService/updateInfoPointGathererConfig
    payload: {{d:infopoint_config}}
  delete:
    title: Delete information points.
    description: Provide an id or an list of ids of information points (-i) as parameter.
    example: -i 1326,1327
    method: POST
    endpoint: /controller/restui/informationPointUiService/deleteInformationPoints
    payload: [{{i:information_points}}]
```
